# Generated by Django 5.1.1 on 2024-09-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentRoomCustomer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
