# Generated by Django 5.1.1 on 2024-10-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentRoomCustomer', '0004_product_address_product_city_product_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='city',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_Fully_Furnished',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_sharable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='state',
        ),
        migrations.RemoveField(
            model_name='product',
            name='zipcode',
        ),
    ]
