# Generated by Django 5.1.1 on 2024-10-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentRoomCustomer', '0006_product_address_product_city_product_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extension',
            field=models.CharField(default='', max_length=10),
        ),
    ]
