# Generated by Django 5.1.1 on 2024-10-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentRoomCustomer', '0007_product_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amenities',
            field=models.CharField(default='', max_length=200),
        ),
    ]
