# Generated by Django 5.1.1 on 2024-10-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentRoomCustomer', '0010_product_old_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_bookmark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
