# Generated by Django 5.1.1 on 2024-10-06 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentRoomCustomer', '0011_profile_old_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_bookmark',
        ),
    ]
